apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/VVenkatamanisai/gitops-demo
    targetRevision: main
    path: helm/nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
